import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'
import Beliefs from '../components/Beliefs'
import Details from '../components/Details'
import Testimonials from '../components/Testimonials'
import Contact from '../components/Contact'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gallant Solutions LLC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <Beliefs />
        <Details />
        <Testimonials />
        <Contact />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
